"""add_journal_entry_id_to_idempotency_records

Revision ID: 67a7b755039d
Revises: 7bb8fd203663
Create Date: 2026-08-29 15:40:39.934464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67a7b755039d'
down_revision: Union[str, Sequence[str], None] = '7bb8fd203663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('accounts', 'type',
               existing_type=postgresql.ENUM('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', name='accounttype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.add_column('idempotency_records', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('idempotency_records', sa.Column('journal_entry_id', sa.UUID(), nullable=True))
    op.alter_column('idempotency_records', 'response_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(),
               nullable=True)
    op.alter_column('idempotency_records', 'status_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_idempotency_records_key'), 'idempotency_records', ['key'], unique=True)
    op.create_foreign_key(None, 'idempotency_records', 'journal_entries', ['journal_entry_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_journal_entries_idempotency_key'), table_name='journal_entries')
    op.drop_column('journal_entries', 'idempotency_key')
    op.alter_column('postings', 'direction',
               existing_type=postgresql.ENUM('DEBIT', 'CREDIT', name='direction'),
               type_=sa.String(length=6),
               existing_nullable=False)
    op.drop_index(op.f('idx_posting_account_created'), table_name='postings')
    op.drop_index(op.f('ix_postings_account_id'), table_name='postings')
    op.drop_index(op.f('ix_postings_journal_entry_id'), table_name='postings')
    op.drop_constraint(op.f('postings_journal_entry_id_fkey'), 'postings', type_='foreignkey')
    op.create_foreign_key(None, 'postings', 'journal_entries', ['journal_entry_id'], ['id'], ondelete='CASCADE')
    op.drop_column('postings', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postings', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint('postings_journal_entry_id_fkey', 'postings', type_='foreignkey')
    op.create_foreign_key(op.f('postings_journal_entry_id_fkey'), 'postings', 'journal_entries', ['journal_entry_id'], ['id'])
    op.create_index(op.f('ix_postings_journal_entry_id'), 'postings', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_postings_account_id'), 'postings', ['account_id'], unique=False)
    op.create_index(op.f('idx_posting_account_created'), 'postings', ['account_id', 'created_at'], unique=False)
    op.alter_column('postings', 'direction',
               existing_type=sa.String(length=6),
               type_=postgresql.ENUM('DEBIT', 'CREDIT', name='direction'), postgresql_using='direction::direction',
               existing_nullable=False)
    op.add_column('journal_entries', sa.Column('idempotency_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_journal_entries_idempotency_key'), 'journal_entries', ['idempotency_key'], unique=True)
    op.drop_constraint('idempotency_records_journal_entry_id_fkey', 'idempotency_records', type_='foreignkey')
    op.drop_index(op.f('ix_idempotency_records_key'), table_name='idempotency_records')
    op.alter_column('idempotency_records', 'status_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('idempotency_records', 'response_payload',
               existing_type=sa.String(),
               type_=postgresql.JSONB(astext_type=sa.Text()), postgresql_using='response_payload::jsonb',
               nullable=True)
    op.drop_column('idempotency_records', 'journal_entry_id')
    op.drop_column('idempotency_records', 'id')
    op.alter_column('accounts', 'type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', name='accounttype'),
               existing_nullable=False, postgresql_using='type::accounttype')
    op.alter_column('accounts', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
