"""Add external_transactions table for reconciliation

Revision ID: 7e439f48f1f1
Revises: dfc16bb48d9f
Create Date: 2026-08-29 16:58:05.441741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e439f48f1f1'
down_revision: Union[str, Sequence[str], None] = 'dfc16bb48d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('idempotency_records', 'status_code',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=3, scale=0),
               nullable=False)
    op.alter_column('idempotency_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('idempotency_records_journal_entry_id_fkey'), 'idempotency_records', type_='foreignkey')
    op.create_foreign_key(None, 'idempotency_records', 'journal_entries', ['journal_entry_id'], ['id'])
    op.drop_column('idempotency_records', 'response_payload')
    op.alter_column('journal_entries', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('journal_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.add_column('postings', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('postings', 'direction',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.create_index('ix_postings_journal_entry_id', 'postings', ['journal_entry_id'], unique=False)
    op.drop_constraint(op.f('postings_journal_entry_id_fkey'), 'postings', type_='foreignkey')
    op.create_foreign_key(None, 'postings', 'journal_entries', ['journal_entry_id'], ['id'])
    op.create_table('external_transactions',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('source', sa.String(length=100), nullable=False),
        sa.Column('external_ref', sa.String(length=255), nullable=False),
        sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('match_status', sa.Enum('UNMATCHED', 'EXACT_MATCH', 'WINDOW_MATCH', 'MANUAL_REVIEW', 'RESOLVED', name='matchstatus'), nullable=False),
        sa.Column('matched_posting_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['matched_posting_id'], ['postings.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('external_ref')
    )
    op.create_index(op.f('ix_external_transactions_external_ref'), 'external_transactions', ['external_ref'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_transactions_external_ref'), table_name='external_transactions')
    op.drop_table('external_transactions')
    op.execute('DROP TYPE IF EXISTS matchstatus')
    op.drop_constraint('postings_journal_entry_id_fkey', 'postings', type_='foreignkey')
    op.create_foreign_key(op.f('postings_journal_entry_id_fkey'), 'postings', 'journal_entries', ['journal_entry_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_postings_journal_entry_id', table_name='postings')
    op.alter_column('postings', 'direction',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    op.drop_column('postings', 'created_at')
    op.alter_column('journal_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('journal_entries', 'description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('idempotency_records', sa.Column('response_payload', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('idempotency_records_journal_entry_id_fkey', 'idempotency_records', type_='foreignkey')
    op.create_foreign_key(op.f('idempotency_records_journal_entry_id_fkey'), 'idempotency_records', 'journal_entries', ['journal_entry_id'], ['id'], ondelete='SET NULL')
    op.alter_column('idempotency_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('idempotency_records', 'status_code',
               existing_type=sa.Numeric(precision=3, scale=0),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###